# API Contract: Todo Chatbot Local Kubernetes Deployment

**Feature**: Phase IV - Local Kubernetes Deployment
**Date**: 2026-01-05
**Version**: 1.0.0

## Overview

This contract defines the internal and external API contracts for the Todo Chatbot deployed on local Minikube Kubernetes cluster. The frontend and backend services communicate via internal ClusterIP services, while the frontend is accessible externally via NodePort.

## Internal Service Communication

### Frontend to Backend

**Protocol**: HTTP/1.1
**Security**: Internal Kubernetes network (ClusterIP service)
**Base URL**: `http://todo-chatbot-backend:8000`

#### Frontend API Dependencies

| Endpoint | Method | Description | Auth Required |
|-----------|----------|-------------|----------------|
| `POST /api/chat` | Create or continue conversation | Yes (JWT) |
| `GET /api/conversations` | List user conversations | Yes (JWT) |
| `DELETE /api/conversations/{id}` | Delete conversation | Yes (JWT) |

---

## Backend API Contract

**Version**: 1.0.0
**Base URL**: `http://todo-chatbot-backend:8000/api`
**Content-Type**: `application/json`

### Authentication

All API endpoints require JWT token in Authorization header.

```http
Authorization: Bearer <JWT_TOKEN>
```

**Token Source**: Frontend receives JWT from login endpoint (from Phase II), stores in localStorage, and sends with each request.

### Endpoints

#### POST /api/auth/login

Authenticate user and return JWT token.

**Request Body**:
```json
{
  "email": "user@example.com",
  "password": "password123"
}
```

**Response** (200 OK):
```json
{
  "access_token": "eyJhbGciOiJIUzI1NiJ9...",
  "token_type": "bearer",
  "expires_in": 3600
}
```

**Errors**:
- 401 Unauthorized: Invalid credentials
- 422 Unprocessable Entity: Invalid request format

---

#### GET /api/health

Health check endpoint for Kubernetes liveness/readiness probes.

**Response** (200 OK):
```json
{
  "status": "healthy",
  "timestamp": "2026-01-05T12:00:00Z",
  "version": "1.0.0"
}
```

---

#### POST /api/chat

Send chat message and receive AI response with streaming.

**Headers**:
```http
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json
```

**Request Body**:
```json
{
  "message": "Add a task to buy groceries tomorrow",
  "conversation_id": "optional-existing-conversation-id"
}
```

**Response** (200 OK, Server-Sent Events):
```json
{
  "conversation_id": "conv-uuid-123",
  "message_id": "msg-uuid-456",
  "content": "I'll add that task for you. ✓ Added task: Buy groceries (due tomorrow)",
  "tool_calls": [
    {
      "tool_name": "add_task",
      "parameters": {
        "title": "Buy groceries",
        "due_date": "2026-01-06"
      },
      "result": {
        "id": "task-789",
        "title": "Buy groceries",
        "due_date": "2026-01-06",
        "completed": false
      }
    }
  ]
}
```

**Errors**:
- 401 Unauthorized: Invalid or expired JWT
- 429 Too Many Requests: Rate limit exceeded (30 req/min)
- 500 Internal Server Error: AI service unavailable

**Streaming**: Response is sent via Server-Sent Events (SSE) for real-time updates.

---

#### GET /api/conversations

List all conversations for authenticated user.

**Headers**:
```http
Authorization: Bearer <JWT_TOKEN>
```

**Query Parameters**:
- `limit` (optional, default 50, max 100): Number of conversations to return
- `offset` (optional, default 0): Pagination offset

**Response** (200 OK):
```json
{
  "conversations": [
    {
      "id": "conv-uuid-123",
      "title": "Buy groceries task",
      "created_at": "2026-01-05T10:30:00Z",
      "updated_at": "2026-01-05T10:35:00Z",
      "message_count": 5
    }
  ],
  "total": 25,
  "limit": 50,
  "offset": 0
}
```

**Errors**:
- 401 Unauthorized: Invalid or expired JWT

---

#### DELETE /api/conversations/{id}

Delete a conversation and all its messages.

**Headers**:
```http
Authorization: Bearer <JWT_TOKEN>
```

**Path Parameters**:
- `id`: Conversation UUID

**Response** (200 OK):
```json
{
  "id": "conv-uuid-123",
  "deleted": true
}
```

**Errors**:
- 401 Unauthorized: Invalid or expired JWT
- 404 Not Found: Conversation doesn't exist or belongs to different user
- 403 Forbidden: User doesn't have permission to delete this conversation

---

## Kubernetes Service Contract

### Service Names

| Service | Type | Port | External Access |
|---------|------|------|-----------------|
| todo-chatbot-frontend | NodePort | 3000 | Via minikube service (NodePort 30000-32767) |
| todo-chatbot-backend | ClusterIP | 8000 | Internal only |

### Service Discovery

**Frontend Service**:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-chatbot-frontend
  namespace: todo-chatbot
  labels:
    app: todo-chatbot
    component: frontend
spec:
  type: NodePort
  selector:
    app: todo-chatbot
    component: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
```

**Backend Service**:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-chatbot-backend
  namespace: todo-chatbot
  labels:
    app: todo-chatbot
    component: backend
spec:
  type: ClusterIP
  selector:
    app: todo-chatbot
    component: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
```

---

## Configuration Contract

### ConfigMap (Non-Secret)

**Name**: `todo-chatbot-config`

**Data**:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-chatbot-config
  namespace: todo-chatbot
data:
  # Frontend configuration
  FRONTEND_API_URL: "http://todo-chatbot-backend:8000"
  LOG_LEVEL: "INFO"
  NODE_ENV: "production"

  # Backend configuration
  DATABASE_URL: "postgresql://user:pass@host:5432/db"
  OPENAI_MODEL: "gpt-4o-mini"
  MAX_CONVERSATION_HISTORY: "20"
```

### Secret (Sensitive)

**Name**: `todo-chatbot-secrets`

**Data** (Base64-encoded):
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-chatbot-secrets
  namespace: todo-chatbot
type: Opaque
stringData:
  JWT_SECRET: "base64-encoded-jwt-secret"
  OPENAI_API_KEY: "base64-encoded-openai-api-key"
```

**Creating Secret**:
```bash
kubectl create secret generic todo-chatbot-secrets \
    --from-literal=JWT_SECRET='your-jwt-secret-here' \
    --from-literal=OPENAI_API_KEY='your-openai-api-key-here' \
    -n todo-chatbot
```

---

## Health Check Contract

### Frontend Health Check

**Endpoint**: `GET /healthz` or `GET /`

**Response** (200 OK):
```json
{
  "status": "healthy",
  "service": "frontend",
  "version": "1.0.0"
}
```

**Probe Configuration**:
```yaml
livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
```

---

### Backend Health Check

**Endpoint**: `GET /api/health`

**Response** (200 OK):
```json
{
  "status": "healthy",
  "service": "backend",
  "version": "1.0.0",
  "database": "connected",
  "dependencies": {
    "database": "ok",
    "openai": "ok"
  }
}
```

**Probe Configuration**:
```yaml
livenessProbe:
  httpGet:
    path: /api/health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
```

---

## Deployment Contract

### Deployment Specifications

**Frontend Deployment**:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-chatbot-frontend
  namespace: todo-chatbot
  labels:
    app: todo-chatbot
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: todo-chatbot
      component: frontend
  template:
    metadata:
      labels:
        app: todo-chatbot
        component: frontend
    spec:
      containers:
      - name: frontend
        image: todo-chatbot-frontend:local-dev
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: FRONTEND_API_URL
          valueFrom:
            configMapKeyRef:
              name: todo-chatbot-config
              key: FRONTEND_API_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: todo-chatbot-config
              key: LOG_LEVEL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: todo-chatbot-config
              key: NODE_ENV
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
```

**Backend Deployment**:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-chatbot-backend
  namespace: todo-chatbot
  labels:
    app: todo-chatbot
    component: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: todo-chatbot
      component: backend
  template:
    metadata:
      labels:
        app: todo-chatbot
        component: backend
    spec:
      containers:
      - name: backend
        image: todo-chatbot-backend:local-dev
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: todo-chatbot-config
              key: DATABASE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: todo-chatbot-config
              key: LOG_LEVEL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: todo-chatbot-secrets
              key: OPENAI_API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: todo-chatbot-secrets
              key: JWT_SECRET
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
```

---

## Versioning

**API Versioning**: URL-based versioning (`/api/v1/`)

**Helm Chart Versioning**: Semantic versioning (0.1.0)

**Container Image Versioning**: Tag-based (local-dev, 1.0.0, etc.)

---

## Error Handling

### Error Response Format

```json
{
  "error": {
    "code": "ERROR_CODE",
    "message": "Human-readable error message",
    "details": {}
  }
}
```

### Error Codes

| Code | HTTP Status | Description |
|------|-------------|-------------|
| AUTH_INVALID | 401 | Invalid or expired JWT token |
| AUTH_MISSING | 401 | Authorization header missing |
| RATE_LIMIT_EXCEEDED | 429 | Too many requests (30 req/min) |
| VALIDATION_ERROR | 422 | Invalid request format |
| NOT_FOUND | 404 | Resource not found |
| INTERNAL_ERROR | 500 | Internal server error |

---

## Testing

### Local Testing Commands

```bash
# Test frontend health
curl http://localhost:3000/healthz

# Test backend health
curl http://localhost:8000/api/health

# Test backend login
curl -X POST http://localhost:8000/api/auth/login \
  -H "Content-Type: application/json" \
  -d '{"email": "test@example.com", "password": "password123"}'

# Test chat endpoint (requires JWT)
curl -X POST http://localhost:8000/api/chat \
  -H "Authorization: Bearer <JWT_TOKEN>" \
  -H "Content-Type: application/json" \
  -d '{"message": "Show my tasks"}'
```

### Kubernetes Testing

```bash
# Test health from inside cluster
kubectl run -it --rm debug --image=curlimages/curl:7.68.0 --restart=Never -- http://todo-chatbot-backend:8000/api/health
kubectl run -it --rm debug --image=curlimages/curl:7.68.0 --restart=Never -- http://todo-chatbot-frontend:3000/healthz

# Port-forward to test locally
kubectl port-forward -n todo-chatbot svc/todo-chatbot-frontend 3000:3000
kubectl port-forward -n todo-chatbot svc/todo-chatbot-backend 8000:8000
```
